data:
  basics_url: "https://datasets.imdbws.com/title.basics.tsv.gz"
  ratings_url: "https://datasets.imdbws.com/title.ratings.tsv.gz"
  crew_url: "https://datasets.imdbws.com/title.crew.tsv.gz"
  cache_db: "imdb.duckdb"
  sample_frac: 1.0        # при полном обучении 1.0, для теста можно 0.1
  random_state: 42

features:
  hashing_vectorizer_n_features: 500   # вместо TF-IDF
  text_column: "primaryTitle"

model:
  sgd_params:
    max_iter: 1000
    tol: 0.001
    learning_rate: "optimal"   # или "adaptive"
    alpha: 0.001              # вместо 0.0001
    penalty: "l2"
    random_state: 42

train:
  chunk_size: 100000
  sample_for_imputer: 100000
  test_size: 0.2
  random_state: 42

paths:
  model_dir: "models"
  model_filename: "sgd_model.pkl"
  vectorizer_filename: "hashing_vectorizer.pkl"
  imputer_filename: "imputer.pkl"
  director_avg_filename: "director_avg.pkl"
  metadata_filename: "metadata.json"